POST http://localhost:8080/poihr/api/vacation/vac-req/save
Content-Type: application/json

{
  "vacTypeId": 2,
  "vacUseDays": 1,
  "startDate": "2025-03-02",
  "endDate": "2025-03-06",
  "reason": "배아파서요"
}