POST http://localhost:8080/author/add
Content-Type: application/json

{
  "employeeNumber": "EMP002",
  "employeeName": "김철수",
  "gender": "M",
  "address": "서울시 송파구",
  "email": "kim@example.com",
  "password": "1234",
  "phone": "010-2222-3333",
  "employeeIdentity": "950101-1234567",
  "employeeStatus": "ACTIVE",
  "levelId": 1,
  "deptId": 2,
  "positionId": 3
}
