PATCH http://localhost:8080/author/1
Content-Type: application/json

{
  "employeeName": "박성리",
  "address": "서울특별시 강남구 테헤란로 123",
  "email": "seongri.park@example.com",
  "phone": "010-2222-3333",
  "employeeIdentity": "900101-1234567",
  "employeeStatus": "ACTIVE",
  "password": "newSecurePassword123!",
  "gender": "M",
  "levelId": 1
}

